### ISSUE TITLE
typo3 11 compatibility

### ISSUE THREAD

**Issue by SMA-cgn** [teamneusta/modmod#4]
Hi, thanks for this great extension!
Do you plan to release an updated version for typo3 11?

Thanks!

**Comment by BobMali** [comment]
Thanks for your kind words!
TYPO3 v11 compatibility is available with release 2.0.0. 👍🏽

**Comment by SMA-cgn** [comment]
Hi, thanks a lot!!!   Just tested it and works!  :)

I noticed one small issue - the author of a comment is not shown. Instead there is a ()

![image](https://github.com/teamneusta/modmod/assets/109371753/60d425d0-4e20-4032-a83a-26d348e4f19d)

It would be great if this could be enhanced.

**Comment by BobMali** [comment]
> Hi, thanks a lot!!! Just tested it and works! :)
> 
> I noticed one small issue - the author of a comment is not shown. Instead there is a ()
> 
> ![image](https://private-user-images.githubusercontent.com/109371753/268684727-60d425d0-4e20-4032-a83a-26d348e4f19d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTMyODYsIm5iZiI6MTcwMTY5Mjk4NiwicGF0aCI6Ii8xMDkzNzE3NTMvMjY4Njg0NzI3LTYwZDQyNWQwLTRlMjAtNDAzMi1hODNhLTI2ZDM0OGU0ZjE5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQxMjI5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzdlYTFhZTgyODM3MzdmNDcwZWViY2IxY2RmZjI3MDUzNGJlYzNkMjlmOGQ5MzBiODJjZDNkNTc3YTBkM2NiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E90pta1toejB3elkHY4ITMFpF4EW1dhY5MIwWmByTLY)
> 
> It would be great if this could be enhanced.

I can't reproduce this behaviour without further information. Could you please open a new bug issue if the behaviour still persists?

Regards
